safe:        false
port: 4000
url: http://crisscrossed.github.io/eiti
#url: http://localhost:4000

destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   date

rdiscount:
  extensions: []

year: 2012

locales:
  es:
    title_message: EITI Perú
    slogan_message: "Revelando la información de las industrias extractivas"
    navigation:
    - text: Inicio
      url: /index.html
    - text: Ingresos
      url: /ingresos/index.html
    - text: Empresas
      url: /empresas/index.html
    - text: Distribucion
      url: /distribucion/index.html
    - text: "Enlaces de Interés"
      url: /Enlaces/index.html
    - text: Glosario
      url: /glosario/index.html

  en:
    title_message: EITI Peru Transparency
    slogan_message: Research and analyse extractives industries
    navigation:
    - text: Global Engagement
      url: /en/index.html
    - text: Sectors
      url: /en/sektoren/index.html
    - text: Results
      url: /en/wirkungen/index.html
    - text: Source of funds
      url: /en/mittelherkunft/index.html
    - text: About this website
      url: /en/ueber/index.html
prose:
  rooturl: _includes/editables
